Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/FileName:
  Exclude:
    - 'lib/nihaopay-ruby.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

EndOfLine:
  Enabled: false
